nginx:
     build: ./nginx/
     container_name: nginx-container
     ports:
     - 800:800
     links:
     - php
     volumes_from:
     - app-data
php:
     build: ./php/
     container_name: php-container
     expose: 
     - 9000
     volumes_from: 
     - app-data
app-data:
     image: php:7.4-fpm  
     container_name: app-data-container  
     volumes:  
     - ./www/html/:/var/www/html/
     command: "true"